Members Only
Rocio01/solo_members pull request #3
Opened 2020-11-13 17:19 UTC by Rocio01

Greetings 
This is an exclusive clubhouse app where the members can write embarrassing posts about non-members. Inside the clubhouse, members can see who the author of a post is but, outside, they can only see the story and wonder who wrote it.
Built it with Ruby on Rails using:
- Models, Views, and Controllers (MVC)
- Data Structures & Relationships
- Routing
- Migrations
- Views with forms, partials, and helpers
- RESTful design
- Adding gems for extra features

Thanks for your attention.

2020-11-13 20:08 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## What a remarkable project you have built 💯! This is impressive 🤩👌🧨!

### But in order to get it approved, we need to work on some changes. Let's see...

- When creating a new post, you don't need the `author` input field. You are already getting the `author` name from the logged-in user (`current_user.name`). 

I have left some additional comments below. Be sure to check them out.

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-11-13 20:08 UTC, tirthajyoti-ghosh commented on config/routes.rb
> +  resources :posts
- [x] The `:posts` routes should only contain `:new`, `:create`, and  `:index` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_routes_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication)).

  ```ruby
  resources :posts, only: [:new, :create, :index]
  ```

2020-11-13 20:08 UTC, tirthajyoti-ghosh commented on app/views/home/_header.html.erb
> +    <% if user_signed_in? %>
There should be absolutely NO logic in views. 
>Views are only for displaying information that became available to it from its corresponding controller not generating it.      

**Resources**
- [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
- [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
- [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

- [x] Please remove all logic from all of the view files (except the ones generated by `devise`).

2020-11-13 20:08 UTC, tirthajyoti-ghosh commented on app/controllers/posts_controller.rb
> +  # before_action :correct_user, only: [:edit, :update, :destroy]
Please remove all commented codes. If you want to access past codes, use git history.

2020-11-13 20:08 UTC, tirthajyoti-ghosh commented on app/controllers/posts_controller.rb
> +    # @post = current_user.posts.build
Please also remove this commented code. This is just one place where I have pointed out. Please go through your project and remove all commented codes.

2020-11-13 20:08 UTC, tirthajyoti-ghosh commented on app/models/user.rb
> +  has_many :friends
I think you meant `has_many :posts` here. There are no model called `friends` in your project. 
Please update this.

2020-11-13 20:08 UTC, tirthajyoti-ghosh commented on app/controllers/posts_controller.rb
> +  before_action :authenticate_user!, except: %i[index show]
You need to use a custom `before_action` method to restrict access to the `:new` and `:create` methods (the custom method should be defined in ApplicationController) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/before_action_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication)).

2020-11-13 20:08 UTC, tirthajyoti-ghosh commented on app/controllers/posts_controller.rb
> +    params.require(:post).permit(:title, :body, :author, :user_id)
This is not the right way to pass the `user_id` to create a new post. This poses a major security risk. Instead, use 
`current_user.posts.build(post_params)` to create a new post.

This way you are relying on rails sessions to handle user authorization, which is much more secure than passing `user_id` as params.

2020-11-13 20:08 UTC, tirthajyoti-ghosh commented on app/views/posts/_form.html.erb
> +  </div>
Please remove this hidden input field. Any logged-in user can alter the `value` attribute and pose as a different author. This is a huge security flaw. 

I have already discussed a solution above. Please follow that and remove this input field.

2020-11-13 20:08 UTC, tirthajyoti-ghosh commented on app/views/posts/_form.html.erb
> +  </div>
This field is unnecessary. You can just display the name/username of the author of the post. Asking for the author's name is unnecessary.

Please remove this field. Also, remember to remove the `author` field from the `posts` table.

2020-11-18 18:08 UTC, mcrd25 approved these changes
# Changes approved :heavy_check_mark: 

Hi Team! :wave: 

Good job implementing requested changes and recognizing where you had technically alreadly implementedwhat was asked.

I see no need for further review. Maybe you can consider adding tests in the future and adding a helper method to test whether a user is signed in to be used in views.
This will make the project look even more impressive.

***If you have any questions, now or in the future, do not hesitate to contact me on social media, email or on slack and I will be glad to chat with you.***

*Happy coding 😄,*
**[--Maya Douglas](mayacdouglas.com)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

2020-11-18 19:10 UTC, merged